### ISSUE TITLE
Questions for Alex

### ISSUE THREAD

**Issue by vanderbeam** [EditLLC/law-template#2]
Alex, the issues I've been having:
- The contact form not showing up (I've tried several templates and all of them remove everything except the message field)
- For some reason my Staff pictures for "Bob" and "Lala" aren't showing up after closing the info. I've even tried copy/pasting the picture for "Joe" (whose picture shows up fine) and it still cuts out on the second click. The only difference is that Bob and Lala are .jpg and Joe is .jpeg, but that shouldn't effect it, right?

**Comment by rodneystrong** [comment]
Good stuff. This is just to clarify for posterity's sake that you resolved this. 

The contact form not showing up was due to a CSS rule that forced invisibility. Specifically:

input {
  visibility: hidden;
  position: absolute;
}

I remember you mentioned you were able to solve the alignment with the staff pictures.

Good work!

**Comment by rodneystrong** [comment]
Actually, i'll have to re-open this : ( 

It looks like the input fields still don't show up. 

![screen shot 2015-08-04 at 4 52 46 pm](https://cloud.githubusercontent.com/assets/539962/9075425/6abf1d78-3ac9-11e5-80f2-6f853864fa8c.png)

**Comment by vanderbeam** [comment]
@rodneystrong They're there, I just have it styles without a border or initial background (unless it's focused). I assume you want me to change that to avoid confusion?

**Comment by rodneystrong** [comment]
Aaaah, then yes, in that case, please put a different colored background to avoid confusion and make it clear to the visitor where the input fields are.

**Comment by vanderbeam** [comment]
This is done

**Comment by rodneystrong** [comment]
good work ma'am! thanks for seein things my way.
