### ISSUE TITLE
menu automatically opens on resize

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/law-template#3]
![screen shot 2015-08-04 at 4 52 15 pm](https://cloud.githubusercontent.com/assets/539962/9075440/9d968f74-3ac9-11e5-9b66-1ee75071205d.png)

Please make it so it's closed to the "pancake" icon by default which then requires the user to click on that "pancake" to see the menu on smaller screens.

due:
8-5-15    5p

**Comment by vanderbeam** [comment]
This is done

**Comment by rodneystrong** [comment]
nice!
