### ISSUE TITLE
Figure out a way to change arrow on toggle

### ISSUE THREAD

**Issue by vanderbeam** [EditLLC/law-template#4]
In the #action section I'm trying to get the arrow to flip up and down on toggle in the bootstrap accordion header (see screenshot): 
![1](https://cloud.githubusercontent.com/assets/12962001/9187204/b13ac988-3f82-11e5-89e1-bbbfbdf63bd6.png)
![2](https://cloud.githubusercontent.com/assets/12962001/9187203/b13a7cb2-3f82-11e5-953e-5a5a462433de.png)

**Comment by vanderbeam** [comment]
This is pushed.

**Comment by rodneystrong** [comment]
i'm so fuckin proud of you. good work finding a solution and implementing it.
